services:
  db:
    image: postgres:16
    container_name: simple_lms_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: simple_lms_redis
    restart: always
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:7
    container_name: simple_lms_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: simple_lms_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: .
    container_name: simple_lms_web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - mongodb
      - rabbitmq   
    
  celery-worker:
    build: .
    container_name: simple_lms_celery_worker
    command: celery -A config worker -l info
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq

  celery-beat:
    build: .
    container_name: simple_lms_celery_beat
    command: celery -A config beat -l info
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - celery-worker
  flower:
    build: .
    container_name: simple_lms_flower
    command: celery -A config flower --port=5555
    restart: always
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - celery-worker
volumes:
  postgres_data:
  mongodb_data: